title: Html Content Block Docs
description: A Confluence Html Content Block Macro for displaying HTML pages in Confluence.
theme: just-the-docs

url: https://aurorasean.github.io/Html-Content-Block-Site/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
